# Aron Baugh
## Week 11 - 4/4/2021
### Python Numpy universal functions

In [3]:
import numpy as np

arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18]

z=[]

for i, j in zip(arr1,arr2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26]

In [4]:
#zip

fname = ("Alice","Bob","Christy")
lname = ("Charlie","Clark","Robert")

flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Robert'))


In [5]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [6]:
import numpy as np

arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [7]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [15]:
arr1 = np.random.randn(10)
arr1

array([-0.25341479,  1.1851182 ,  0.18925679,  1.71744619,  0.13020163,
       -0.51093293, -1.43608082,  0.3513483 ,  0.77760192, -1.02836195])

In [16]:
arr2 = np.random.randn(10)
arr2

array([ 0.69393131,  0.71312085,  0.82891776, -0.34541773,  0.97181136,
        0.89839372, -1.02452824,  1.31720443, -0.89786972,  0.89558676])

In [17]:
np.add(arr1,arr2)

array([ 0.44051651,  1.89823905,  1.01817455,  1.37202846,  1.10201299,
        0.38746079, -2.46060906,  1.66855273, -0.1202678 , -0.13277519])

In [18]:
np.maximum(arr1,arr2)

array([ 0.69393131,  1.1851182 ,  0.82891776,  1.71744619,  0.97181136,
        0.89839372, -1.02452824,  1.31720443,  0.77760192,  0.89558676])

In [20]:
#np.where
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
print(arr <4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [22]:
np.where(arr < 4, -1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [23]:
np.where((arr < 4) & (arr > 2), -1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [24]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]


In [26]:
arr3 = [r1 if c else r1, r2, c in zip(arr1,arr2,arr_b)]
arr3

NameError: name 'c' is not defined

In [27]:
#using np.where
arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])