# Aron Baugh
## Week 11 - 4/4/2021
### Python Numpy universal functions

In [2]:
import numpy as np

arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18]

z=[]

for i, j in zip(arr1,arr2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26]

In [4]:
#zip

fname = ("Alice","Bob","Christy")
lname = ("Charlie","Clark","Robert")

flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Robert'))


In [5]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [6]:
import numpy as np

arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [7]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [15]:
arr1 = np.random.randn(10)
arr1

array([-0.25341479,  1.1851182 ,  0.18925679,  1.71744619,  0.13020163,
       -0.51093293, -1.43608082,  0.3513483 ,  0.77760192, -1.02836195])

In [16]:
arr2 = np.random.randn(10)
arr2

array([ 0.69393131,  0.71312085,  0.82891776, -0.34541773,  0.97181136,
        0.89839372, -1.02452824,  1.31720443, -0.89786972,  0.89558676])

In [17]:
np.add(arr1,arr2)

array([ 0.44051651,  1.89823905,  1.01817455,  1.37202846,  1.10201299,
        0.38746079, -2.46060906,  1.66855273, -0.1202678 , -0.13277519])

In [18]:
np.maximum(arr1,arr2)

array([ 0.69393131,  1.1851182 ,  0.82891776,  1.71744619,  0.97181136,
        0.89839372, -1.02452824,  1.31720443,  0.77760192,  0.89558676])

In [20]:
#np.where
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
print(arr <4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [22]:
np.where(arr < 4, -1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [23]:
np.where((arr < 4) & (arr > 2), -1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [24]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]


In [26]:
arr3 = [r1 if c else r1, r2, c in zip(arr1,arr2,arr_b)]
arr3

NameError: name 'c' is not defined

In [27]:
#using np.where
arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])

In [3]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
cond = np.array([[True,False],[True,True]])
np.where(cond,arr1,arr2)

array([[1, 6],
       [3, 4]])

In [4]:
np.where([[True,False],[True,True]],[[5,6],[7,8]],[[1,2],[3,4]])

array([[5, 2],
       [7, 8]])

In [5]:
from numpy.random import randn
arr = randn(5,5)
arr

array([[-2.7392718 ,  1.13782205, -0.67153986, -1.30675558, -0.22889279],
       [ 2.12508839,  0.74704329, -0.83972615,  0.48559768,  0.43400836],
       [ 1.44211629, -0.43869448,  0.54065511,  0.96205294,  0.7623574 ],
       [ 0.21589986,  0.58274419,  0.62540152, -1.10699263, -0.22860533],
       [-0.04860591,  0.07220552, -0.79890089,  1.21829912, -1.86776251]])

In [6]:
np.where(arr<0, 0,arr)

array([[0.        , 1.13782205, 0.        , 0.        , 0.        ],
       [2.12508839, 0.74704329, 0.        , 0.48559768, 0.43400836],
       [1.44211629, 0.        , 0.54065511, 0.96205294, 0.7623574 ],
       [0.21589986, 0.58274419, 0.62540152, 0.        , 0.        ],
       [0.        , 0.07220552, 0.        , 1.21829912, 0.        ]])

In [7]:
arr_b = np.array([True,False,True,False,False])
arr_b.any()

True

In [8]:
arr_b.all()

False

In [9]:
fruits = np.array(['Apple','Cherry','Apple','Orange','Cherry','Banana'])
np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [10]:
np.in1d(['Apple','Cherry','Grape'],fruits)

array([ True,  True, False])

In [11]:
#statistical measures
arr = np.array([[1,2,3,],[4,5,6],[7,8,9,]])
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
arr.sum()

45

In [13]:
arr.sum(0)

array([12, 15, 18])

In [14]:
arr.sum(1)

array([ 6, 15, 24])

In [15]:
print(arr)
np.sum(arr, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [16]:
arr.mean()

5.0

In [17]:
print(arr)
arr.mean(0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [18]:
np.mean(arr,axis=0)

array([2., 5., 8.])

In [19]:
np.mean(arr,axis=0)

array([4., 5., 6.])

In [20]:
arr.var()

6.666666666666667

In [21]:
arr.std()

2.581988897471611

In [22]:
arr = np.array([3,6,8,1,2,9,10,15,16,122])
arr.sort()
arr

array([  1,   2,   3,   6,   8,   9,  10,  15,  16, 122])

In [23]:
#identify array
i = np.eye(5)

i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
a = np.arange(25).reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
a * i

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0., 24.]])

In [27]:
i = np.eye(2)
print(i)
a = np.arange(4).reshape((2,2))
print(a)
a*i

[[1. 0.]
 [0. 1.]]
[[0 1]
 [2 3]]


array([[0., 0.],
       [0., 3.]])

In [28]:
m = np.mat([[1,2],[3,4]])
m

matrix([[1, 2],
        [3, 4]])

In [29]:
m * i

matrix([[1., 2.],
        [3., 4.]])

In [30]:
#Transpose

arr = np.array([[1,2,3,4,],[5,6,7,8]])

print(arr.shape)
print(arr)
print('---------------')
t = arr.T
t

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
---------------


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [31]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [32]:
arr.transpose((0,1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
arr.transpose((1,0))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [34]:
arr_3d = np.arange(20).reshape((2,5,2))

print(arr_3d)
print(arr_3d.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)


In [35]:
arr_3d.transpose(((0,1,2)))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [36]:
arr_3d.transpose(((1,0,2)))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [38]:
np.random.random((4,4))

array([[0.04733992, 0.75741429, 0.77164322, 0.88047477],
       [0.47206454, 0.14897108, 0.10600159, 0.76863395],
       [0.93616857, 0.39326341, 0.34355445, 0.79333504],
       [0.43317457, 0.73154946, 0.29228078, 0.08298292]])

In [39]:
from numpy.random import random

In [40]:
random((4,4))

array([[0.63034517, 0.1615285 , 0.7358664 , 0.86128398],
       [0.15139412, 0.10946088, 0.34267617, 0.34332722],
       [0.35392539, 0.62415532, 0.16259659, 0.92334243],
       [0.57275032, 0.756916  , 0.211893  , 0.33693856]])

In [42]:
from numpy.random import randn
randn(5,5)

array([[ 0.52896618, -0.24054334, -1.09574672,  0.43902006, -0.07612618],
       [ 1.47094088, -0.20634076, -0.39645453,  0.25889972, -0.6272024 ],
       [ 0.41938425,  0.08189946,  1.2044323 ,  2.17088988, -0.4976141 ],
       [ 0.40544128, -0.27346159,  0.94395665,  1.33802487,  0.01714102],
       [ 0.03754643,  0.18497817, -0.35212408,  0.24410336, -0.8533826 ]])

In [43]:
randn(5)

array([-0.32033458, -1.37486687, -1.73026225, -0.08732254,  0.59168863])

In [45]:
np.random.randint(10,50)

21

In [48]:
website = "https://docs.spicy.org/doc/numpy/reference/ufuncs.html#available-unfuncs"

import webbrowser
webbrowser.open(website)

True

In [50]:
import pandas as pd